[workspace]
members = [
  "packages/swc-plugin-compiler/plugin",
  "packages/swc-plugin-compiler/visitor",
]

[profile.release]
codegen-units = 1
# debug = true
# lto = true

# Optimize for size
opt-level = "s"

# Strip debug symbols
strip = "symbols"
