[package]
name = "narrative-swc-compiler-visitor"
version = "0.1.0"
authors = ["Joe_Sky <hitomi_doax@sina.com>"]
description = "SWC plugin for compiling Narrative tags to runtime code."
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
swc_core = { version = "0.82.11", features = ["ecma_plugin_transform"] }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
regex = "1.5.4"

[dev-dependencies]
testing = "0.33.13"
swc_core = { version = "0.82.11", features = [
  "testing_transform",
  "ecma_parser",
] }
