[package]
name = "narrative-swc-compiler-visitor"
version = "0.1.0"
authors = ["Joe_Sky <hitomi_doax@sina.com>"]
description = "SWC plugin for compile and enhance the limitation of Narrative runtime code."
license = "MIT"
edition = "2021"

[dependencies]
easy-error = "1.0.0"
serde = "1"
swc_core = { version = "0.76.0", features = ["ecma_plugin_transform"] }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }

[dev-dependencies]
testing = "0.33.8"
swc_core = { version = "0.76.0", features = [
  "testing_transform",
  "ecma_parser",
] }
